name: tests

on: [ push,pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: (1/4) Checkout the repository
        uses: actions/checkout@v5

      - name: (2/4) Setup JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: temurin

      - name: (3/4) Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: (4/4) Run tests
        run: ./gradlew --stacktrace --no-configuration-cache test
